import { ProductItem, ServiceItem, TestimonialItem, PathStep, CertificationItem } from './types';

export const WHATSAPP_PHONE = '593962669994';
export const WHATSAPP_DEFAULT_MSG = 'Hola Casa Kinti, me gustaría obtener más información sobre sus servicios y productos.';

export const PATH_STEPS_HOLISTICA: PathStep[] = [
  {
    number: '01',
    keyword: 'CONECTA',
    title: 'Conoce tu Esencia',
    description: 'Diagnóstico bioenergético con péndulo para comprender tu momento vital.',
    icon: 'Eye',
    accentColor: '#2B7294',
  },
  {
    number: '02',
    keyword: 'SANA',
    title: 'Limpias & Botánica',
    description: 'Liberación de bloqueos mediante limpias ancestrales y plantas sagradas.',
    icon: 'Leaf',
    accentColor: '#043651',
  },
  {
    number: '03',
    keyword: 'EQUILIBRA',
    title: 'Plantas Sagradas del Pensamiento',
    description: 'Ceremonias sagradas con preparación y acompañamiento integral antes, durante y después.',
    icon: 'Scale',
    accentColor: '#2B7294',
  },
  {
    number: '04',
    keyword: 'FLORECE',
    title: 'Transformación Plena',
    description: 'Paz interior profunda, vitalidad renovada y bienestar integral.',
    icon: 'Flower2',
    accentColor: '#043651',
  },
];

export const PATH_STEPS_EDUCACION: PathStep[] = [
  {
    number: '01',
    keyword: 'EVALÚA',
    title: 'Diagnóstico Integral',
    description: 'Evaluación psicopedagógica del estilo y potencial de aprendizaje.',
    icon: 'Brain',
    accentColor: '#CEAB67',
  },
  {
    number: '02',
    keyword: 'ESTIMULA',
    title: 'Inmersión Bilingüe',
    description: 'Estimulación temprana y lúdica del lenguaje en inglés y español.',
    icon: 'BookOpen',
    accentColor: '#043651',
  },
  {
    number: '03',
    keyword: 'ACOMPAÑA',
    title: 'Pautas para el Hogar',
    description: 'Estrategias y rutinas amigables de estudio para toda la familia.',
    icon: 'GraduationCap',
    accentColor: '#CEAB67',
  },
  {
    number: '04',
    keyword: 'CRECE',
    title: 'Seguridad & Éxito',
    description: 'Confianza, autonomía y felicidad en cada etapa escolar.',
    icon: 'Sparkles',
    accentColor: '#D4B26F',
  },
];

export const PATH_STEPS = PATH_STEPS_HOLISTICA;

export const CERTIFICATIONS: CertificationItem[] = [
  {
    title: 'Educadora Infantil Bilingüe',
    institution: 'Formación Superior Universitaria',
    icon: 'GraduationCap',
    highlight: 'Especialista en desarrollo infantil y estimulación bilingüe temprana',
  },
  {
    title: 'Máster en Problemas de Aprendizaje',
    institution: 'Postgrado Académico',
    icon: 'Brain',
    highlight: 'Diagnóstico psicopedagógico y adecuación curricular personalizada',
  },
  {
    title: 'Ceremonias con Plantas Sagradas del Pensamiento',
    institution: 'Casa Kinti',
    icon: 'Leaf',
    highlight: 'Preparación y acompañamiento antes, durante y después',
  },
  {
    title: 'Mujer Medicina Certificada',
    institution: 'Medicina Ancestral y Tradición Andina',
    icon: 'Sparkles',
    highlight: 'Limpias energéticas con péndulo, sahumerios y lectura de oráculos',
  },
];

export const PRODUCTS: ProductItem[] = [
  {
    id: 'aceites-esenciales-personalizados',
    name: 'Aceites Esenciales Personalizados',
    price: '$15.00',
    description: 'Mezclas personales formuladas a medida según tu energía y necesidad terapéutica. Presentación en frasco de vidrio de 20ml con esencias botánicas 100% puras.',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
    badge: 'Mezclas Personales',
    category: 'Aromaterapia & Esencias',
    benefits: ['Frasco de vidrio de 20ml', 'Mezclas personales a medida', 'Esencias botánicas 100% puras'],
    popular: true,
  },
  {
    id: 'cuarzos-consagrados-proteccion',
    name: 'Cuarzos Consagrados para Protección',
    price: '$15.00',
    description: 'Cristales y cuarzos naturales ritualizados y activados específicamente para protección energética, absorción de densidades y elevación de tu frecuencia vibratoria.',
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    badge: 'Consagración Ritual',
    category: 'Amuletos & Cristales',
    benefits: ['Cuarzo natural consagrado', 'Escudo de protección energética', 'Transmutación de vibraciones densas'],
    popular: true,
  },
  {
    id: 'kit-sahumerios-sales-bano',
    name: 'Kit de Sahumerios Naturales & Sales de Baño',
    price: '$12.00',
    description: 'Kit ritual completo con sahumerios naturales y sales de baño enriquecidas con aceites esenciales, diseñadas para baños de limpieza y purificación en casa.',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80',
    badge: 'Kit Purificación',
    category: 'Kits Rituales',
    benefits: ['Sahumerios de hierbas naturales', 'Sales de baño con aceites esenciales', 'Limpieza y purificación en casa'],
    popular: true,
  },
  {
    id: 'pulseras-energeticas',
    name: 'Pulseras de Protección',
    price: '$12.00',
    description: 'Pulseras consagradas elaboradas con elementos de poder natural para acompañarte en tu día a día, blindando tu energía y campo áurico.',
    image: '/pulseras-amuletos.png',
    badge: 'Amuleto Protector',
    category: 'Amuletos & Cristales',
    benefits: ['Piedras y cuentas naturales', 'Consagración energética personal', 'Protección áurica cotidiana'],
  },
];

export const COURSES_EDUCACION: ProductItem[] = [
  {
    id: 'curso-estimulacion-bilingue',
    name: 'Taller Continuo de Estimulación Bilingüe',
    price: '$45.00 / módulo',
    description: 'Programa lúdico de inmersión en inglés y español para potenciar el lenguaje, la motricidad fina y la socialización en edades tempranas (2 a 6 años).',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80',
    badge: 'Inscripciones Abiertas',
    category: 'Talleres Bilingües',
    benefits: ['Inmersión lingüística natural', 'Material sensorial incluido', 'Grupos reducidos y personalizados'],
    popular: true,
  },
  {
    id: 'curso-padres-aprendizaje',
    name: 'Curso para Padres: Manejo de Dificultades de Aprendizaje',
    price: '$35.00',
    description: 'Herramientas prácticas, rutinas y estrategias psicopedagógicas para acompañar el estudio en casa sin estrés ni frustración familiar.',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    badge: 'Formato Online / Híbrido',
    category: 'Escuela para Familias',
    benefits: ['Guías y plantillas descargables', 'Estrategias para TDAH y dislexia', 'Asesoría directa con Johanna Proaño'],
    popular: true,
  },
  {
    id: 'kit-material-didactico',
    name: 'Kit de Material Didáctico Multisensorial + Guía Pedagógica',
    price: '$28.00',
    description: 'Set de fichas interactivas, juegos sensoriales y cuadernillo de estimulación cognitiva diseñado para reforzar la lectura, escritura y concentración.',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80',
    badge: 'Material Físico + Guía',
    category: 'Materiales & Guías',
    benefits: ['Material didáctico de alta durabilidad', 'Guía de actividades paso a paso', 'Estimulación cognitiva y motriz'],
    popular: true,
  },
  {
    id: 'programa-nivelacion-escolar',
    name: 'Programa de Nivelación y Refuerzo Pedagógico Integral',
    price: '$60.00 / mes',
    description: 'Acompañamiento individualizado y continuo para superar bloqueos escolares en lectoescritura, razonamiento lógico y hábitos de estudio.',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    badge: 'Atención 1 a 1',
    category: 'Refuerzo Académico',
    benefits: ['Evaluación diagnóstica inicial', 'Coordinación con la institución educativa', 'Reportes mensuales de avance para padres'],
  },
  {
    id: 'taller-lectoescritura-creativa',
    name: 'Taller de Lectoescritura Creativa & Fonética en Inglés',
    price: '$25.00 / taller',
    description: 'Enfoque fonético y multisensorial (Jolly Phonics) para que los niños aprendan a leer y escribir con entusiasmo y confianza.',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    badge: 'Método Lúdico',
    category: 'Talleres Bilingües',
    benefits: ['Sonidos fonéticos y juegos interactivos', 'Desarrollo de comprensión lectora', 'Fichas de práctica ilustradas'],
  },
  {
    id: 'guia-psicopedagogica-descargable',
    name: 'Guía Digital: Rutinas y Hábitos de Estudio Exitosos',
    price: '$12.00',
    description: 'Ebook y planificador imprimible con técnicas de concentración, pausas activas y métodos de estudio probados para la etapa escolar.',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80',
    badge: 'Descarga Inmediata',
    category: 'Materiales & Guías',
    benefits: ['Planificadores semanales imprimibles', 'Técnicas de gestión del tiempo para niños', 'Consejos para motivar sin castigos'],
  },
];

export const SERVICES_ANCESTRAL: ServiceItem[] = [
  {
    id: 'tarot-completo',
    title: 'Lectura de Tarot Completa',
    price: '$35.00',
    description: 'Sesión integral y profunda que incluye lectura general de tu momento vital, respuesta detallada a 6 preguntas específicas y canalización espiritual con lectura de Ángeles y Ancestros.',
    category: 'ancestral',
    icon: 'Eye',
    badge: 'Más Solicitado',
    duration: '60 min',
    image: '/tarot-hero.png',
    keyBenefits: ['Lectura general profunda', '6 preguntas específicas canalizadas', 'Lectura de Ángeles y Ancestros'],
  },
  {
    id: 'tarot-express',
    title: 'Lectura Express de Tarot',
    price: '$20.00',
    description: 'Orientación clara, ágil y precisa para resolver encrucijadas inmediatas. Incluye lectura general del panorama energético y 3 preguntas específicas.',
    category: 'ancestral',
    icon: 'Eye',
    badge: 'Sesión Express',
    duration: '30 min',
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Lectura general del panorama', '3 preguntas específicas', 'Orientación clara y al punto'],
  },
  {
    id: 'psicoterapia-honguitos',
    title: 'Psicoterapia Asistida con Honguitos',
    price: '$120.00',
    description: 'Proceso terapéutico profundo de medicina enteógena guiada por Johanna Proaño. Paquete integral de 4 sesiones de sanación, autoconocimiento e integración consciente.',
    category: 'ancestral',
    icon: 'Sparkles',
    badge: '4 Sesiones',
    duration: 'Paquete 4 Sesiones',
    image: '/hero-holistica-tambor.jpg',
    keyBenefits: ['Paquete de 4 sesiones guiadas', 'Medicina enteógena sagrada', 'Acompañamiento e integración terapéutica'],
  },
  {
    id: 'psicoterapia-registros-akashicos',
    title: 'Psicoterapia con Registros Akáshicos',
    price: '$80.00',
    description: 'Apertura de tus memorias del alma y psicoterapia holística para comprender el origen de bloqueos, patrones repetitivos y sanar contratos kármicos. Paquete de 2 sesiones.',
    category: 'ancestral',
    icon: 'Brain',
    badge: '2 Sesiones',
    duration: 'Paquete 2 Sesiones',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Paquete de 2 sesiones completas', 'Apertura de Registros Akáshicos', 'Sanación de linaje y patrones kármicos'],
  },
  {
    id: 'ceremonia-ayahuasca-puyo',
    title: 'Ceremonia de Ayahuasca en el Puyo',
    price: '$160.00',
    description: 'Inmersión ceremonial de 2 días en la selva del Puyo con la medicina sagrada Ayahuasca. Purga física y espiritual, dietas ancestrales y guía chamánica experta.',
    category: 'ancestral',
    icon: 'Leaf',
    badge: 'Retiro 2 Días',
    duration: '2 Días (Puyo)',
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Experiencia de 2 días en el Puyo', 'Toma ceremonial de medicina ancestral', 'Purificación profunda y guía personalizada'],
  },
  {
    id: 'ceremonia-union-pareja',
    title: 'Ceremonia de Unión de Pareja',
    price: '$120.00',
    description: 'Ritual sagrado de unión consciente y bendición de almas. Ceremonia con los cuatro elementos sagrados, armonización áurica y consagración de compromisos espirituales.',
    category: 'ancestral',
    icon: 'Flower',
    badge: 'Ritual Sagrado',
    duration: '90 - 120 min',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Ritual sagrado de bendición de unión', 'Armonización de los 4 elementos', 'Consagración de lazos de almas'],
  },
  {
    id: 'ceremonia-cacao-mujeres',
    title: 'Ceremonia de Cacao y Círculo de Mujeres',
    price: '$120.00',
    description: 'Encuentro sagrado de medicina del corazón con cacao puro ceremonial, cantos ancestrales, meditación, danza y tejido de sabiduría femenina.',
    category: 'ancestral',
    icon: 'Sparkles',
    badge: 'Círculo Sagrado',
    duration: '3 Horas',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Medicina del cacao puro ceremonial', 'Círculo de palabra y empoderamiento femenino', 'Cantos de sanación y apertura del corazón'],
  },
];

export const SERVICES_EDUCACION: ServiceItem[] = [
  {
    id: 'asesoria-aprendizaje',
    title: 'Asesoría en Problemas de Aprendizaje',
    price: '$35.00',
    description: 'Evaluación y acompañamiento a padres y niños con dificultades de aprendizaje, déficit de atención o dislexia, basado en la formación de Máster de Johanna Proaño.',
    category: 'educacion',
    icon: 'Brain',
    badge: 'Especialidad Máster',
    duration: '60 min',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Estrategias adaptadas al ritmo del niño', 'Asesoría a padres y docentes', 'Plan de intervención psicopedagógico'],
  },
  {
    id: 'talleres-bilingues',
    title: 'Talleres de Educación Bilingüe Infantil',
    price: '$18.00',
    description: 'Talleres lúdicos en español e inglés para estimulación temprana, desarrollo del lenguaje y motricidad, dirigidos por educadora infantil certificada.',
    category: 'educacion',
    icon: 'Languages',
    duration: '50 min por sesión',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Inmersión lingüística natural y afectiva', 'Metodología lúdica con canciones y juegos', 'Grupos reducidos para atención cercana'],
  },
  {
    id: 'evaluacion-psicopedagogica',
    title: 'Evaluación Psicopedagógica Inicial',
    price: '$40.00',
    description: 'Diagnóstico integral para identificar el estilo de aprendizaje del niño, fortalezas cognitivas y diseñar un plan de acompañamiento personalizado.',
    category: 'educacion',
    icon: 'CheckSquare',
    badge: 'Recomendado para inicio',
    duration: '75 min',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Informe pedagógico detallado para padres', 'Detección temprana de necesidades especiales', 'Recomendaciones prácticas para el aula y hogar'],
  },
];

export const INCLUDED_EXPERIENCE_ITEMS = [
  'Diagnóstico energético y educativo inicial',
  'Plan personalizado de terapias o talleres adaptado a tu ritmo',
  'Seguimiento cercano con agenda flexible presencial o virtual',
  'Acceso a productos energéticos recomendados para ti',
  'Acompañamiento continuo vía WhatsApp durante todo tu proceso',
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'María Fernanda L.',
    role: 'Limpia & Medicina Ancestral',
    text: 'Las limpias energéticas con Johanna me devolvieron la calma y la vitalidad que había perdido hace meses. El ambiente de Casa Kinti transmite una paz absoluta desde que cruzas la puerta.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    area: 'ancestral',
  },
  {
    id: 'test-2',
    name: 'Andrea Salazar',
    role: 'Ceremonias con Plantas Sagradas del Pensamiento',
    text: 'La ceremonia con Plantas Sagradas del Pensamiento fue profundamente sanadora. La preparación previa y el acompañamiento amoroso de Johanna antes, durante y después me brindaron una contención, seguridad y paz invaluables.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    area: 'ancestral',
  },
  {
    id: 'test-3',
    name: 'Patricia Morales',
    role: 'Lectura de Tarot Terapéutico',
    text: 'Fue una sesión con preguntas claras y enfoque de autoconocimiento sin misterios innecesarios. Me dio una dirección nítida para desbloquear decisiones personales cruciales.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    area: 'ancestral',
  },
  {
    id: 'test-4',
    name: 'Valeria Rosales',
    role: 'Armonización Áurica & Sahumerio',
    text: 'Llegué con una sobrecarga emocional muy densa. La armonización con hierbas sagradas andinas y el sonido me dejaron liviana y con una claridad mental maravillosa.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    area: 'ancestral',
  },
  {
    id: 'test-5',
    name: 'Gabriel Benítez',
    role: 'Diagnóstico Radiestésico con Péndulo',
    text: 'El diagnóstico energético fue exacto en los puntos de bloqueo que sentía en mi cuerpo. El amuleto y las recomendaciones de Johanna transformaron mi energía en el trabajo.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    area: 'ancestral',
  },
];

export const CONTACT_INFO = {
  address: 'Av. Eloy Alfaro N32-15 y Av. Amazonas, Quito, Ecuador',
  hours: 'Lunes a Viernes 9:00 – 18:00 | Sábados 9:00 – 14:00 | Domingos cerrado',
  phone: '+593 96 266 9994',
  whatsappRaw: '593962669994',
  email: 'contacto@casakinti.com',
  tiktok: 'https://www.tiktok.com/@johapro3',
  instagram: 'https://www.instagram.com/casa_kinti_',
  facebook: 'https://www.facebook.com/casakinti',
  googleMapsEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.7901198544976!2d-78.4878!3d-0.1807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91d59a7a67f1b2ef%3A0x7d94d3c333240e8a!2sAv.%20Eloy%20Alfaro%20%26%20Av.%20Amazonas%2C%20Quito%2C%20Ecuador!5e0!3m2!1ses!2sec!4v1700000000000!5m2!1ses!2sec',
};
