import { ProductItem, ServiceItem, TestimonialItem, PathStep, CertificationItem } from './types';

export const WHATSAPP_PHONE = '593962669994';
export const WHATSAPP_DEFAULT_MSG = 'Hola Casa Kinti, me gustaría obtener más información sobre sus servicios y productos.';

export const PATH_STEPS_HOLISTICA: PathStep[] = [
  {
    number: '01',
    keyword: 'CONECTA',
    title: 'Conoce tu Esencia',
    description: 'Diagnóstico bioenergético con péndulo para comprender tu momento vital.',
    icon: 'Eye',
    accentColor: '#2B7294',
  },
  {
    number: '02',
    keyword: 'SANA',
    title: 'Limpias & Botánica',
    description: 'Liberación de bloqueos mediante limpias ancestrales y plantas sagradas.',
    icon: 'Leaf',
    accentColor: '#043651',
  },
  {
    number: '03',
    keyword: 'EQUILIBRA',
    title: 'Plantas Sagradas del Pensamiento',
    description: 'Ceremonias sagradas con preparación y acompañamiento integral antes, durante y después.',
    icon: 'Scale',
    accentColor: '#2B7294',
  },
  {
    number: '04',
    keyword: 'FLORECE',
    title: 'Transformación Plena',
    description: 'Paz interior profunda, vitalidad renovada y bienestar integral.',
    icon: 'Flower2',
    accentColor: '#043651',
  },
];

export const PATH_STEPS_EDUCACION: PathStep[] = [
  {
    number: '01',
    keyword: 'DESCUBRE',
    title: 'Cada Niño es Único',
    description: 'Acompañamiento respetando el ritmo, intereses, talentos y manera individual de aprender.',
    icon: 'Brain',
    accentColor: '#CEAB67',
  },
  {
    number: '02',
    keyword: 'INTEGRA',
    title: 'Montessori & Educación Consciente',
    description: 'Educación alternativa, principios Montessori y herramientas de terapias integrativas.',
    icon: 'BookOpen',
    accentColor: '#043651',
  },
  {
    number: '03',
    keyword: 'NIVELA',
    title: 'Acompañamiento Escolar',
    description: 'Fortalecimiento de contenidos en Lengua, Matemática, Inglés y Comprensión Lectora.',
    icon: 'GraduationCap',
    accentColor: '#CEAB67',
  },
  {
    number: '04',
    keyword: 'DISFRUTA',
    title: 'Confianza & Autonomía',
    description: 'Desarrollo de hábitos de estudio y seguridad para volver a disfrutar del aprendizaje.',
    icon: 'Sparkles',
    accentColor: '#D4B26F',
  },
];

export const PATH_STEPS = PATH_STEPS_HOLISTICA;

export const CERTIFICATIONS: CertificationItem[] = [
  {
    title: 'Educadora Infantil Bilingüe',
    institution: 'Formación Superior Universitaria',
    icon: 'GraduationCap',
    highlight: 'Especialista en desarrollo infantil y estimulación bilingüe temprana',
  },
  {
    title: 'Máster en Problemas de Aprendizaje',
    institution: 'Postgrado Académico',
    icon: 'Brain',
    highlight: 'Diagnóstico psicopedagógico y adecuación curricular personalizada',
  },
  {
    title: 'Ceremonias con Plantas Sagradas del Pensamiento',
    institution: 'Casa Kinti',
    icon: 'Leaf',
    highlight: 'Preparación y acompañamiento antes, durante y después',
  },
  {
    title: 'Mujer Medicina Certificada',
    institution: 'Medicina Ancestral y Tradición Andina',
    icon: 'Sparkles',
    highlight: 'Limpias energéticas con péndulo, sahumerios y lectura de oráculos',
  },
];

export const PRODUCTS: ProductItem[] = [
  {
    id: 'aceites-esenciales-personalizados',
    name: 'Aceites Esenciales Personalizados',
    price: '$15.00',
    description: 'Mezclas personales formuladas a medida según tu energía y necesidad terapéutica. Presentación en frasco de vidrio de 20ml con esencias botánicas 100% puras.',
    image: '/aceites-esenciales.jpg',
    badge: 'Mezclas Personales',
    category: 'Aromaterapia & Esencias',
    benefits: ['Frasco de vidrio de 20ml', 'Mezclas personales a medida', 'Esencias botánicas 100% puras'],
    popular: true,
  },
  {
    id: 'cuarzos-consagrados-proteccion',
    name: 'Cuarzos Consagrados para Protección',
    price: '$15.00',
    description: 'Cristales y cuarzos naturales ritualizados y activados específicamente para protección energética, absorción de densidades y elevación de tu frecuencia vibratoria.',
    image: '/cuarzos-consagrados.jpg',
    badge: 'Consagración Ritual',
    category: 'Amuletos & Cristales',
    benefits: ['Cuarzo natural consagrado', 'Escudo de protección energética', 'Transmutación de vibraciones densas'],
    popular: true,
  },
  {
    id: 'kit-sahumerios-sales-bano',
    name: 'Kit de Sahumerios Naturales & Sales de Baño',
    price: '$12.00',
    description: 'Kit ritual completo con sahumerios naturales y sales de baño enriquecidas con aceites esenciales, diseñadas para baños de limpieza y purificación en casa.',
    image: '/sales-bano-sahumerios.png',
    badge: 'Kit Purificación',
    category: 'Kits Rituales',
    benefits: ['Sahumerios de hierbas naturales', 'Sales de baño con aceites esenciales', 'Limpieza y purificación en casa'],
    popular: true,
  },
  {
    id: 'pulseras-energeticas',
    name: 'Pulseras de Protección',
    price: '$12.00',
    description: 'Pulseras consagradas elaboradas con elementos de poder natural para acompañarte en tu día a día, blindando tu energía y campo áurico.',
    image: '/pulseras-amuletos.png',
    badge: 'Amuleto Protector',
    category: 'Amuletos & Cristales',
    benefits: ['Piedras y cuentas naturales', 'Consagración energética personal', 'Protección áurica cotidiana'],
  },
];

export const TEACHING_METHODS_EDUCACION = [
  {
    id: 'metodo-educacion-alternativa',
    title: 'Educación Alternativa',
    badge: 'Método de Enseñanza',
    description: 'Procesos de aprendizaje activos y respetuosos donde cada niño es visto como un ser único, despertando su curiosidad natural e intereses genuinos.',
    image: '/metodo-educacion-alternativa.jpg',
    benefits: ['Aprendizaje activo y significativo', 'Respeto al ritmo individual', 'Desarrollo de talentos únicos'],
    whatsappMessage: 'Hola Casa Kinti, deseo conocer más sobre su método de Educación Alternativa.',
  },
  {
    id: 'metodo-principios-montessori',
    title: 'Principios Montessori',
    badge: 'Método de Enseñanza',
    description: 'Entornos preparados y materiales concretos y sensoriales que fomentan la concentración, la autonomía y la autoconfianza para aprender.',
    image: '/metodo-principios-montessori.jpg',
    benefits: ['Materiales multisensoriales concretos', 'Autonomía y toma de decisiones', 'Concentración y gozo por aprender'],
    whatsappMessage: 'Hola Casa Kinti, deseo conocer más sobre la integración de Principios Montessori.',
  },
  {
    id: 'metodo-estrategias-personalizadas',
    title: 'Estrategias Pedagógicas Personalizadas',
    badge: 'Método de Enseñanza',
    description: 'Acompañamiento psicopedagógico individualizado para nivelación, comprensión y desarrollo de hábitos y estrategias de estudio amigables.',
    image: '/metodo-estrategias-personalizadas.jpg',
    benefits: ['Atención 1 a 1 adaptada a sus necesidades', 'Fortalecimiento de la seguridad escolar', 'Técnicas amigables de estudio'],
    whatsappMessage: 'Hola Casa Kinti, deseo conocer más sobre las Estrategias Pedagógicas Personalizadas.',
  },
  {
    id: 'metodo-terapias-integrativas',
    title: 'Herramientas de Terapias Integrativas',
    badge: 'Método de Enseñanza',
    description: 'Acompañamiento respetuoso y humano que integra herramientas terapéuticas para la contención emocional, la calma y el bienestar integral del niño.',
    image: '/metodo-terapias-integrativas.jpg',
    benefits: ['Mirada humana y consciente', 'Contención y seguridad emocional', 'Bienestar integral para el aprendizaje'],
    whatsappMessage: 'Hola Casa Kinti, deseo conocer más sobre las Herramientas de Terapias Integrativas.',
  },
];

export const COURSES_EDUCACION: ProductItem[] = [
  {
    id: 'prog-lengua-literatura',
    name: 'Acompañamiento en Lengua y Literatura',
    price: 'Acompañamiento Personalizado',
    description: 'Fortalecimiento de lectoescritura, ortografía, redacción y expresión verbal respetando el ritmo y estilo de aprendizaje de cada niño.',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80',
    badge: 'Lengua & Literatura',
    category: 'Acompañamiento Escolar',
    benefits: ['Lectura comprensiva y fluidez', 'Redacción y ortografía amigable', 'Atención individual a su ritmo'],
    popular: true,
  },
  {
    id: 'prog-matematica',
    name: 'Nivelación & Razonamiento en Matemática',
    price: 'Estrategias Lúdicas & Montessori',
    description: 'Comprensión conceptual profunda a través de material concreto y visual, desarrollando el pensamiento lógico-matemático con alegría y sin frustración.',
    image: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?auto=format&fit=crop&w=800&q=80',
    badge: 'Matemática Activa',
    category: 'Razonamiento Lógico',
    benefits: ['Operaciones básicas y lógica', 'Resolución práctica de problemas', 'Confianza matemática sin ansiedad'],
    popular: true,
  },
  {
    id: 'prog-ingles',
    name: 'Inmersión & Refuerzo en Inglés',
    price: 'Formato Bilingüe Adaptativo',
    description: 'Estimulación fonética temprana, ampliación de vocabulario y acompañamiento en tareas escolares con metodología comunicativa y motivadora.',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    badge: 'Inglés Personalizado',
    category: 'Bilingüismo Infantil',
    benefits: ['Fonética y pronunciación clara', 'Inmersión natural y lúdica', 'Refuerzo escolar bilingüe'],
    popular: true,
  },
  {
    id: 'prog-comprension-lectora',
    name: 'Comprensión Lectora, Escritura y Expresión',
    price: 'Desarrollo del Pensamiento',
    description: 'Estrategias dinámicas para descubrir el placer de leer, desarrollar el pensamiento crítico y expresar ideas creativas con soltura y seguridad.',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    badge: 'Comprensión & Creatividad',
    category: 'Lectoescritura',
    benefits: ['Amor por la lectura y libros', 'Técnicas de análisis y síntesis', 'Expresión creativa y narración'],
  },
  {
    id: 'prog-habitos-estudio',
    name: 'Hábitos & Estrategias Amigables de Estudio',
    price: 'Acompañamiento Psicopedagógico',
    description: 'Técnicas de concentración, pausas activas y métodos amigables de estudio para que las tareas escolares dejen de ser motivo de conflicto en el hogar.',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80',
    badge: 'Hábitos de Estudio',
    category: 'Métodos de Aprendizaje',
    benefits: ['Técnicas de concentración y enfoque', 'Rutinas familiares sin estrés', 'Estrategias para TDAH y ritmo propio'],
  },
  {
    id: 'prog-organizacion-autonomia',
    name: 'Organización & Autonomía en el Aprendizaje',
    price: 'Confianza y Autoestima',
    description: 'Guiamos al niño para que comprenda sus capacidades, gane seguridad, gestione su tiempo y vuelva a disfrutar activamente su proceso de aprender.',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    badge: 'Autonomía & Confianza',
    category: 'Desarrollo Integral',
    benefits: ['Planificación y orden escolar', 'Independencia al hacer tareas', 'Mayor seguridad y autoestima'],
  },
];

export const SERVICES_ANCESTRAL: ServiceItem[] = [
  {
    id: 'tarot-completo',
    title: 'Lectura de Tarot Completa',
    price: '$35.00',
    description: 'Sesión integral y profunda que incluye lectura general de tu momento vital, respuesta detallada a 6 preguntas específicas y canalización espiritual con lectura de Ángeles y Ancestros.',
    category: 'ancestral',
    icon: 'Eye',
    badge: 'Más Solicitado',
    duration: '60 min',
    image: '/tarot-lectura-completa.jpg',
    keyBenefits: ['Lectura general profunda', '6 preguntas específicas canalizadas', 'Lectura de Ángeles y Ancestros'],
  },
  {
    id: 'tarot-express',
    title: 'Lectura Express de Tarot',
    price: '$20.00',
    description: 'Orientación clara, ágil y precisa para resolver encrucijadas inmediatas. Incluye lectura general del panorama energético y 3 preguntas específicas.',
    category: 'ancestral',
    icon: 'Eye',
    badge: 'Sesión Express',
    duration: '30 min',
    image: '/tarot-express-cosmico.jpg',
    keyBenefits: ['Lectura general del panorama', '3 preguntas específicas', 'Orientación clara y al punto'],
  },
  {
    id: 'psicoterapia-honguitos',
    title: 'Psicoterapia Asistida con Honguitos',
    price: '$120.00',
    description: 'Proceso terapéutico profundo de medicina enteógena guiada por Johanna Proaño. Paquete integral de 4 sesiones de sanación, autoconocimiento e integración consciente.',
    category: 'ancestral',
    icon: 'Sparkles',
    badge: '4 Sesiones',
    duration: 'Paquete 4 Sesiones',
    image: '/psicoterapia-hongos.jpg',
    keyBenefits: ['Paquete de 4 sesiones guiadas', 'Medicina enteógena sagrada', 'Acompañamiento e integración terapéutica'],
  },
  {
    id: 'psicoterapia-registros-akashicos',
    title: 'Psicoterapia con Registros Akáshicos',
    price: '$80.00',
    description: 'Apertura de tus memorias del alma y psicoterapia holística para comprender el origen de bloqueos, patrones repetitivos y sanar contratos kármicos. Paquete de 2 sesiones.',
    category: 'ancestral',
    icon: 'Brain',
    badge: '2 Sesiones',
    duration: 'Paquete 2 Sesiones',
    image: '/registros-akashicos.jpg',
    keyBenefits: ['Paquete de 2 sesiones completas', 'Apertura de Registros Akáshicos', 'Sanación de linaje y patrones kármicos'],
  },
  {
    id: 'ceremonia-ayahuasca-puyo',
    title: 'Ceremonia de Ayahuasca en el Puyo',
    price: '$160.00',
    description: 'Inmersión ceremonial de 2 días en la selva del Puyo con la medicina sagrada Ayahuasca. Purga física y espiritual, dietas ancestrales y guía chamánica experta.',
    category: 'ancestral',
    icon: 'Leaf',
    badge: 'Retiro 2 Días',
    duration: '2 Días (Puyo)',
    image: '/ceremonia-ayahuasca.jpg',
    keyBenefits: ['Experiencia de 2 días en el Puyo', 'Toma ceremonial de medicina ancestral', 'Purificación profunda y guía personalizada'],
  },
  {
    id: 'ceremonia-union-pareja',
    title: 'Ceremonia de Unión de Pareja',
    price: '$120.00',
    description: 'Ritual sagrado de unión consciente y bendición de almas. Ceremonia con los cuatro elementos sagrados, armonización áurica y consagración de compromisos espirituales.',
    category: 'ancestral',
    icon: 'Flower',
    badge: 'Ritual Sagrado',
    duration: '90 - 120 min',
    image: '/ceremonia-union-pareja.jpg',
    keyBenefits: ['Ritual sagrado de bendición de unión', 'Armonización de los 4 elementos', 'Consagración de lazos de almas'],
  },
  {
    id: 'ceremonia-cacao-mujeres',
    title: 'Ceremonia de Cacao y Círculo de Mujeres',
    price: '$120.00',
    description: 'Encuentro sagrado de medicina del corazón con cacao puro ceremonial, cantos ancestrales, meditación, danza y tejido de sabiduría femenina.',
    category: 'ancestral',
    icon: 'Sparkles',
    badge: 'Círculo Sagrado',
    duration: '3 Horas',
    image: '/ceremonia-cacao-mujeres.jpg',
    keyBenefits: ['Medicina del cacao puro ceremonial', 'Círculo de palabra y empoderamiento femenino', 'Cantos de sanación y apertura del corazón'],
  },
];

export const SERVICES_EDUCACION: ServiceItem[] = [
  {
    id: 'nivelacion-acompanamiento-escolar',
    title: 'Nivelación y Acompañamiento Escolar',
    price: '$30.00',
    description: 'Acompañamos a niños que necesitan fortalecer aprendizajes, recuperar contenidos o desarrollar mayor seguridad en determinadas áreas. Trabajamos a su ritmo con estrategias personalizadas.',
    category: 'educacion',
    icon: 'GraduationCap',
    badge: 'Más Solicitado',
    duration: '60 min',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Refuerzo en Lengua, Matemática e Inglés', 'Estrategias adaptadas al ritmo del niño', 'Seguimiento continuo con informe a padres'],
  },
  {
    id: 'acompanamiento-psicopedagogico',
    title: 'Acompañamiento Psicopedagógico',
    price: '$40.00',
    description: 'Evaluación y acompañamiento integral para niños con dificultades de aprendizaje, déficit de atención o dislexia. Basado en la formación de Máster en Problemas de Aprendizaje de Johanna.',
    category: 'educacion',
    icon: 'Brain',
    badge: 'Especialidad Máster',
    duration: '75 min',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Diagnóstico psicopedagógico integral', 'Plan de intervención personalizado', 'Asesoría y orientación a padres y docentes'],
  },
  {
    id: 'asesoria-aprendizaje',
    title: 'Asesoría en Problemas de Aprendizaje',
    price: '$35.00',
    description: 'Sesión especializada para padres y cuidadores que buscan comprender las necesidades educativas de su hijo y recibir herramientas concretas para apoyarlo desde el hogar.',
    category: 'educacion',
    icon: 'HeartHandshake',
    badge: 'Para padres y familias',
    duration: '60 min',
    image: 'https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Estrategias prácticas para el hogar', 'Comprensión del estilo de aprendizaje', 'Acompañamiento familiar respetuoso'],
  },
  {
    id: 'talleres-bilingues',
    title: 'Talleres de Educación Bilingüe Infantil',
    price: '$18.00',
    description: 'Talleres lúdicos en español e inglés para estimulación temprana, desarrollo del lenguaje y motricidad, dirigidos por educadora infantil certificada.',
    category: 'educacion',
    icon: 'Languages',
    duration: '50 min por sesión',
    image: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Inmersión lingüística natural y afectiva', 'Metodología lúdica con canciones y juegos', 'Grupos reducidos para atención cercana'],
  },
  {
    id: 'evaluacion-psicopedagogica',
    title: 'Evaluación Psicopedagógica Inicial',
    price: '$40.00',
    description: 'Diagnóstico integral para identificar el estilo de aprendizaje del niño, fortalezas cognitivas y diseñar un plan de acompañamiento personalizado.',
    category: 'educacion',
    icon: 'CheckSquare',
    badge: 'Recomendado para inicio',
    duration: '75 min',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    keyBenefits: ['Informe pedagógico detallado para padres', 'Detección temprana de necesidades especiales', 'Recomendaciones prácticas para el aula y hogar'],
  },
];

export const INCLUDED_EXPERIENCE_HOLISTICA = [
  'Diagnóstico bioenergético con péndulo',
  'Limpiezas ancestrales con plantas sagradas y sahumos',
  'Ceremonias con Plantas Sagradas del Pensamiento',
  'Lecturas de Tarot, oráculos y Registros Akáshicos',
  'Amuletos, cuarzos y aceites formulados a tu energía',
  'Acompañamiento presencial en Quito o sesiones virtuales',
];

export const INCLUDED_EXPERIENCE_EDUCACION = [
  'Nivelación y acompañamiento escolar personalizado',
  'Fortalecimiento en Lengua y Literatura',
  'Acompañamiento en Matemática e Inglés',
  'Comprensión lectora, escritura y expresión',
  'Hábitos y estrategias amigables de estudio',
  'Organización, seguridad y autonomía en el aprendizaje',
];

export const INCLUDED_EXPERIENCE_ITEMS = INCLUDED_EXPERIENCE_HOLISTICA;

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'Andrea Salazar',
    role: 'Retiro Terapéutico Ancestral & Medicina',
    text: 'La ceremonia con Plantas Sagradas del Pensamiento fue profundamente sanadora. La preparación previa y el acompañamiento amoroso de Johanna antes, durante y después me brindaron una contención, seguridad y paz invaluables.',
    rating: 5,
    avatar: '/testimonio-retiro-ancestral.jpg',
    area: 'ancestral',
  },
  {
    id: 'test-2',
    name: 'María Fernanda L.',
    role: 'Círculo de Mujeres & Medicina Ancestral',
    text: 'Las limpias energéticas con Johanna me devolvieron la calma y la vitalidad que había perdido hace meses. El ambiente de Casa Kinti transmite una paz absoluta desde que cruzas la puerta.',
    rating: 5,
    avatar: '/testimonio-reencuentro-mujeres.jpg',
    area: 'ancestral',
  },
  {
    id: 'test-3',
    name: 'Valeria Rosales',
    role: 'Armonización Áurica & Meditación',
    text: 'Llegué con una sobrecarga emocional muy densa. La armonización con hierbas sagradas andinas, mandalas florales y el sonido me dejaron liviana y con una claridad mental maravillosa.',
    rating: 5,
    avatar: '/testimonio-meditacion-mandala.jpg',
    area: 'ancestral',
  },
];

export const CONTACT_INFO = {
  address: 'La Merced, Valle de los Chillos, calle César Enrique Balseca y 3 de Mayo, Quito, Ecuador',
  hours: 'Lunes a Viernes 9:00 – 18:00 | Sábados 9:00 – 14:00 | Domingos cerrado',
  phone: '+593 96 266 9994',
  whatsappRaw: '593962669994',
  secondaryPhone: '0983442341',
  secondaryPhoneFormatted: '098 344 2341',
  secondaryWhatsappRaw: '593983442341',
  email: 'contacto@casakinti.com',
  tiktok: 'https://www.tiktok.com/@johapro3',
  instagram: 'https://www.instagram.com/casa_kinti_',
  facebook: 'https://www.facebook.com/casakinti',
  googleMapsUrl: 'https://maps.app.goo.gl/3uZ38akEC6FCT4SU9',
  googleMapsEmbed: 'https://maps.google.com/maps?q=-0.295320,-78.405527&hl=es&z=16&output=embed',
};

